### ISSUE TITLE
Nice (and useful) extension

### ISSUE THREAD

**Issue by giano** [sn4il/indent-tooltip#1]
Thanks for writing it.

Just an issue: shown tooltip does not disappear when changing tab and does not follow scroll.

And my tooltip is very different looking from yours (stylesheet issue probably, with Material Atom Theme)

**Comment by sn4il** [comment]
Thank you for reporting the bug. I'm working on it.

I believe I can make the tooltip disappear on changing tab, however making it follow scroll is kind of tricky (probably won't fix this one). I will also try to fix the styling issue.

**Comment by giano** [comment]
Thank you. I've noticed some other extensions with "tooltips" have the same
issue on scrolling. Probably an Atom wide limitation. If you want this is
my stylesheet for your tooltip (without using the "tooltip-arrow" but an
:after selector)

Have a nice day 😉


>
> @indent_tooltip_color: #FFE58B;
> .tooltip.indent-tooltip__tooltip{
>   margin-left:1em;
> }
> .tooltip.indent-tooltip__tooltip .tooltip-inner {
>     background-color: @indent_tooltip_color;
>     color: darken(@indent_tooltip_color, 50%);
>     padding: 0.2em 0.5em !important;
>     font-size: 0.8em;
> }
> .tooltip.indent-tooltip__tooltip .tooltip-arrow {
>     display: none;
> }
> .tooltip.indent-tooltip__tooltip .tooltip-inner:after {
>     border-color: transparent @indent_tooltip_color transparent
> transparent;
>     content: "";
>     position: absolute;
>     width: 0;
>     height: 0;
>     border-width: 7px;
>     border-style: solid;
>     top: 50%;
>     margin-top: -7px;
>     left: -9px;
> }




2016-06-06 16:13 GMT+02:00 Andrey Malyarchuk <notifications@github.com>:

> Thank you for reporting the bug. I'm working on it.
>
> I believe I can make the tooltip disappear on changing tab, however making
> it follow scroll is kind of tricky (probably won't fix this one). I will
> also try to fix the styling issue.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sn4il/indent-tooltip/issues/1#issuecomment-223971145>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAItKm2xJkpjNTd6ivNC_CjK_hNoVnOhks5qJCsXgaJpZM4IusKD>
> .
>



-- 
Stefano Valicchia - Giardiniere Informatico

Computers are like air conditioners, they stop working properly if you open
Windows.

**Comment by giano** [comment]
Thank you. I've noticed some other extensions with "tooltips" have the same
issue on scrolling. Probably an Atom wide limitation. If you want this is
my stylesheet for your tooltip (without using the "tooltip-arrow" but an
:after selector)

Have a nice day 😉

``` less
@indent_tooltip_color: #FFE58B;

.tooltip.indent-tooltip__tooltip{
  margin-left:1em;
}
.tooltip.indent-tooltip__tooltip .tooltip-inner {
    background-color: @indent_tooltip_color;
    color: darken(@indent_tooltip_color, 50%);
    padding: 0.2em 0.5em !important;
    font-size: 0.8em;
}
.tooltip.indent-tooltip__tooltip .tooltip-arrow {
    display: none;
}
.tooltip.indent-tooltip__tooltip .tooltip-inner:after {
    border-color: transparent @indent_tooltip_color transparent transparent;
    content: "";
    position: absolute;
    width: 0;
    height: 0;
    border-width: 7px;
    border-style: solid;
    top: 50%;
    margin-top: -7px;
    left: -9px;
}
```
